// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Test3
{
	public partial class AnotherViewController : UIViewController
	{
		public AnotherViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
