// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Test3
{
	public partial class SomethingViewCell : UITableViewCell
	{
		public SomethingViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
